theme: jekyll-theme-minimal
title: Mikhail Moiseev — CV
description: Software / Solutions Architect, ex-CTO. 20+ years in IT. Solutions architect with deep expertise in enterprise architecture, microservices and integration.